For each hotel listed in the "Manhattan_selected_to_SLR" workbook, we'll calculate distances from it to all other hotels, and store the result in a new workbook entitled "Hotel Pairwise Distances".

## Imports...

In [28]:
# data manipulation package (provides "dataframe" data structure)
import pandas as pd

# linear algebra / matrix package (provides "ndarray" data structure)
import numpy as np

# vincenty distance formula
from geopy.distance import vincenty

## Getting the Data

First, let's read in the "Names, Addresses, ID, and Coordinates" workbook I put together earlier.

In [20]:
# read in the data
hotel_data = pd.read_excel('../data/Hotel Names, Addresses, ID, and Coordinates.xlsx')

# take a look at the result
hotel_data

,Name,Address,Share ID,Coordinates
0,Homewood Suites New York Midtown Manhattan Tim...,312 W 37th St New York NY 10018-4208,80307,"(40.7542902, -73.9930667)"
1,Hilton New York Fashion District,152 W 26th St New York NY 10001-6801,81620,"(40.7455199, -73.993757)"
2,Holiday Inn New York City Times Square,585 8th Ave New York NY 10018-3003,82671,"(40.755229, -73.99171199999999)"
3,Doubletree New York Times Square South,341 W 36th St New York NY 10018-6401,83645,"(40.7543497, -73.99411900000001)"
4,Hampton Inn ManhattanTimes Square South,337 W 39th St New York NY 10018-1401,83706,"(40.7562619, -73.9928494)"
5,The Ludlow Hotel,180 Ludlow St New York NY 10002-1514,84151,"(40.7218313, -73.98722149999999)"
6,Hotel Le Soleil,38 W 36th St New York NY 10018-8078,84346,"(40.7502658, -73.98548)"
7,W Hotel New York Downtown,8 Albany St New York NY 10006-1001,84511,"(40.7091948, -74.0135809)"
8,Hyatt Times Square,135 W 45th St New York NY 10036-4004,84541,"(40.7575491, -73.98418389999999)"
9,Hilton Garden Inn New York West 35th Street,63 W 35th St New York NY 10001-2202,85007,"(40.7504261, -73.9865346)"
10,Doubletree New York City Chelsea,128 W 29th St New York NY 10001-5301,86091,"(40.7469627, -73.99142719999999)"
11,Holiday Inn Manhattan 6th Avenue Chelsea,125 W 26th St New York NY 10001-6802,86573,"(40.7453825, -73.9922357)"
12,Hotel Chandler,12 E 31st St New York NY 10016-6702,87039,"(40.7459723, -73.985222)"
13,Fairfield Inn & Suites New York Manhattan Cent...,538 W 58th St New York NY 10019-1004,87404,"(40.7704722, -73.98967569999999)"
14,Hilton Garden Inn New York Times Square Central,136 W 42nd St New York NY 10036-7803,87545,"(40.7552669, -73.98607059999999)"
15,Hilton Garden Inn New York Chelsea,121 W 28th St New York NY 10001-6102,88284,"(40.7466303, -73.9914265)"
16,Courtyard New York Manhattan Times Square West,307 W 37th St New York NY 10018,89044,"(40.7544922, -73.9925544)"
17,Walker Hotel Greenwich Village,52 W 13th St New York NY 10011-7902,89567,"(40.7361469, -73.99666169999999)"
18,The Marmara Park Avenue,114 E 32nd St New York NY 10016-5506,89569,"(40.7453037, -73.9816202)"
19,Arlo Hudson Square,231 Hudson St New York NY 10013-1412,91126,"(40.7244391, -74.00823749999999)"
20,Courtyard New York Manhattan Central Park,1717 Broadway New York NY 10019-5214,91329,"(40.764302, -73.9827054)"
21,Holiday Inn New York City Lower East Side,150 Delancey St New York NY 10002-3308,91537,"(40.7182709, -73.9862002)"
22,element New York Times Square West,311 W 39th St New York NY 10018-1401,91697,"(40.7558623, -73.9917756)"
23,Hampton Inn Manhattan Madison Square Garden Area,116 W 31st St New York NY 10001-3401,92168,"(40.748029, -73.9902006)"
24,Hotel Hugo Soho,525 Greenwich St New York NY 10013,92273,"(40.7263865, -74.0087252)"
25,Courtyard New York Manhattan SoHo,181 Varick St New York NY 10014-4602,92349,"(40.7275481, -74.0058074)"
26,InterContinental New York Times Square,300 W 44th St New York NY 10036-5419,92486,"(40.75857, -73.989723)"
27,Hampton Inn Manhattan 35th Street Empire State...,59 W 35th St New York NY 10001-2202,92533,"(40.7503521, -73.9863489)"
28,Four Points by Sheraton Manhattan SoHo Village,66 Charlton St New York NY 10014-4601,92839,"(40.72698, -74.006115)"
29,Four Points by Sheraton Midtown Times Square,326 W 40th St New York NY 10018-1404,93246,"(40.7564022, -73.9923529)"
...,...,...,...,...
148,Hudson Hotel,358 W 58th St New York NY 10019-1804,6159662,"(40.7682097, -73.9848706)"
149,Conrad New York,102 North End Ave New York NY 10282-1238,6236370,"(40.7150015, -74.01522179999999)"
150,Waldorf Astoria New York,301 Park Ave New York NY 10022-6897,6493834,"(40.75651999999999, -73.9734057)"
151,Fifty NYC an Affinia Hotel,155 E 50th St New York NY 10022-9503,6594143,"(40.75610409999999, -73.97095449999999)"
152,Hampton Inn New York Manhattan Times Square North,851 8th Ave New York NY 10019-6237,6744386,"(40.7634278, -73.98595)"
153,St Regis New York,2 E 55th St New York NY 10022-3103,6847121,"(40.7613979, -73.9746128)"
154,Autograph Collection Carlton Hotel,88 Madison Ave New York NY 10016-7412,7221375,"(40.7444291, -73.9857968)"
155,Hilton Manhattan East,304 E 42nd St New York NY 10017-5905,7677157,"(40.7494205, -73.9719069)"
156,Row NYC,700 8th Ave New York NY 10036-3901,7880298,"(40.7587072, -73.9882975)"
157,The Roxy Hotel Tribeca,2 Ave Of The Americas New York NY 10013-2401,8006641,"(40.71938129999999, -74.00478100000001)"
158,Dream Hotel Midtown,210 W 55th St New York NY 10019-5218,8225906,"(40.76442309999999, -73.9819603)"
159,Autograph Collection The Lexington New York City,511 Lexington Ave New York NY 10017-2017,8341862,"(40.7548069, -73.9731814)"
160,Hotel Pennsylvania,401 7th Ave New York NY 10001-3412,8456346,"(40.7499042, -73.99104040000002)"
161,Westin New York Grand Central,212 E 42nd St New York NY 10017-5803,8456912,"(40.7502017, -73.9740114)"
162,Park South Hotel,122 E 28th St New York NY 10016-8402,8563539,"(40.7428157, -73.9831232)"
163,DoubleTree Hotel Metropolitan New York City,569 Lexington Ave New York NY 10022-7501,8763088,"(40.7567148, -73.9714247)"
164,Hilton Millenium Hotel,55 Church St New York NY 10007-2910,8883936,"(40.7111522, -74.01035209999999)"
165,The Gallivant Times Square,234 W 48th St New York NY 10036-1424,9047698,"(40.7605461, -73.9863518)"
166,Millennium One UN,1 United Nations Plz New York NY 10017-3573,9149400,"(40.7504701, -73.96912209999999)"
167,Grand Hyatt New York,109 E 42nd St New York NY 10017-5698,9244498,"(40.7520393, -73.9763424)"
168,Warwick New York Hotel,65 W 54th St New York NY 10019-5404,9266902,"(40.7624022, -73.9782725)"
169,Park Central Hotel,870 7th Ave New York NY 10019-4308,9271414,"(40.7647208, -73.981184)"
170,The Manhattan @ Times Square Hotel,790 7th Ave New York NY 10019-6204,9412233,"(40.761985, -73.9829247)"
171,W Hotel New York Times Square,1567 Broadway New York NY 10036-1517,9498391,"(40.7593257, -73.98559949999999)"
172,The Benjamin,125 E 50th St New York NY 10022-9501,9512243,"(40.7565951, -73.971986)"
173,The Evelyn,7 E 27th St New York NY 10016-8700,9544760,"(40.7439696, -73.9869902)"
174,Novotel New York,226 W 52nd St New York NY 10019-5804,9687125,"(40.7626833, -73.9837907)"
175,Shelburne NYC an Affinia Hotel,303 Lexington Ave New York NY 10016-3165,10082737,"(40.7484908, -73.9779494)"
176,W Hotel Union Square,201 Park Ave S New York NY 10003-1601,10167518,"(40.7366011, -73.9885554)"
177,Marriott New York Downtown,85 West St New York NY 10006-1532,10176414,"(40.7095123, -74.0144893)"

## Calculate Pairwise Distances

For each hotel, calculate the distance from it to all other hotels. The distances will be stored in a 178 x 178 matrix, output in an Excel workbook.

In [47]:
distances = np.zeros((178, 178), dtype=np.float32)

for i, hotel1 in hotel_data.iterrows():
    for k, hotel2 in hotel_data.iterrows():
        distances[i, k] = vincenty(hotel1['Coordinates'], hotel2['Coordinates']).miles

# caste the numpy matrix of distances into a pandas dataframe (indexing / columns with hotel addresses)
distances = pd.DataFrame(distances, index=hotel_data['Name'], columns=hotel_data['Name'])

In [48]:
# write the distances dataframe to an Excel workbook
writer = pd.ExcelWriter('../data/Hotel Pairwise Distances.xlsx')
distances.to_excel(writer, 'Pairwise Distances')
writer.close()